### ISSUE TITLE
A little Help?

### ISSUE THREAD

**Issue by bren1818** [hypergolic/greeenwave_firmware#1]
Hey @hypergolic  - Thanks for posting the firmware, much appreciated. I think I need a little bit of help getting it going.

I was working on my project https://github.com/bren1818/TCPLightingWebInterface where you mentioned yours, and managed to somehow bugger my device. The device boots, however, I can no longer press the sync button, thus I can no longer generate a token. When trying to connect to it I get a 503 service unavailable.

I edited this comment since I figured out how to use your firmware files and didn't want to distract from the issue. My problem initially with Getting the firmware to go, was I'm using pretty consumer grade hardware for my router, so I could not create DNS records on the router, or nat records or use iptables. I ended up installing  http://simpledns.com/, adding two records (greenwavereality.com, update.greenwavereality.com) and then in my host file on my local machine point both of those to 127.0.0.1. Then I had to tell my router to use a custom DNS and pointed it to my desktop ip which was hosting the simple DNS application. From there I loaded up your python server, using the client.pem file , and got the device to finally pull the downgrade (hurray) 

I was still experiencing issues using the the downgraded firmware, had I been smart, I would have sshd in and played around, but instead, I deliberately removed my DNS settings and got the bridge to re-update back to the firmware I was on. This led back to the 503 error.

So I'm now just looking for your feedback, if I go down the rabbit hole , (I'm not super familiar with flashing firmware) and try to reflash it, do you think I'll be able to restore the bridge to stock? Or do you by chance have another stock image file I could try.

Many thanks, enjoy the vacation ,

Cheers,

Bren

What I have to workwith:

Using username "root".
root@192.168.1.108's password:
~ # /etc/init.d/rcS

______________________________________________________________

   .-----.----.-----.-----.-----.--.--.--.---.-.--.--.-----.
   |  _  |   _|  -__|  -__|     |  |  |  |  _  |  |  |  -__|
   |___  |__| |_____|_____|__|__|________|___._|\___/|_____|
   |_____|
                      __ __ __
   .----.-----.---.-.|  |__|  |_.--.--.
   |   _|  -__|  _  ||  |  |   _|  |  |
   |__| |_____|___._||__|__|____|___  |
                                |_____|
______________________________________________________________

 Booting: Apollo3,                             Version: 3.0.39
______________________________________________________________

 * Mounting proc filesystem:                          [FAILED]
 * Mounting sys filesystem:                           [FAILED]
 * Mounting tmpfs filesystem:                         [  OK  ]
 * Starting syslogd:                                  [  OK  ]
 * Starting kernel logger:                            [  OK  ]
 * Creating basic nodes:                              [  OK  ]
 * Loading kernel modules:                            [  OK  ]
 * Using netlink for hotplug events:                  [  OK  ]
 * Starting udev daemon:                              [FAILED]
 * Populating /dev with existing devices:             [  OK  ]
 * Letting udev process events:                       [  OK  ]
 * Mounting mediaconfig:                              [FAILED]
 * Formatting config partition:                       [FAILED]
 *** Mounting mediaconfig:                              [FAILED]
 * Formatting config partition:                       [FAILED]**
 
 The last two will loop fail, which is likely why my device isn't starting correctly. I'm thinking I

**Comment by hypergolic** [comment]
On 2016-10-26 14:30, Bren wrote:

> Hey @hypergolic  - Thanks for posting the firmware, much appreciated.
> I think I need a little bit of help getting it going.
> 
> I was working on my project
> https://github.com/bren1818/TCPLightingWebInterface where mentioned
> yours,  and managed to somehow bugger my device. The device boots,
> however, I can no longer press the sync button, thus I can no longer
> generate a token.
> 
> The power button is lit, but LAN and WAN do not light up. LAN Blinks
> red now and then and if I boot it up holding the sync button then WAN
> will blink.
> 
> I configured my router's dns to point to my local machine. My local
> machine's host file points:
> 
> 127.0.0.1 update.greenwavereality.com
> 127.0.0.1 update.greenwavereality.eu
> 
> I have your project files stored in a folder,
> 
> /download/1349139456/rootfs.bin
> /client.pem (from the rootfs.tar.bz2)
> /rootcert.pem (from the rootfs.tar.bz2)
> /https.py
> /update.php
> 
> I installed python from ninite.com since I haven't really used python
> before (I know - shocking) and ran the https.py
> 
> The window just opens and closes...
> 
> I tried updating the https.py to point to my local machine and to the
> rootcert file
> 
> httpd = BaseHTTPServer.HTTPServer(('192.168.1.101', 443), Handler)
> httpd.socket = ssl.wrap_socket (httpd.socket,
> certfile='./rootcert.pem', server_side=True)
> 
> finally I opened Command Prompt and did the following:
> 
> C:\Python27>python.exe 
> C:\xampp\htdocs\update.greenwavereality.com\roxy\https.py
> 
> and got:
> 
> Traceback (most recent call last):
>   File "C:\xampp\htdocs\update.greenwavereality.com\roxy\https.py",
> line 28, in <module>
>     httpd.socket = ssl.wrap_socket (httpd.socket,
> certfile='./rootcert.pem', server_side=True)
>   File "C:\Python27\lib\ssl.py", line 933, in wrap_socket
>     ciphers=ciphers)
>   File "C:\Python27\lib\ssl.py", line 544, in **init**
>     self._context.load_cert_chain(certfile, keyfile)
> IOError: [Errno 2] No such file or directory
> 
> I'm guessing for whatver reason it isn't finding the file?
> 
> Once this is running, in theory, do all I have to do is start the
> bridge up while holding the sync button?
> 
> My version was the version without the web UI, thus the reason for
> making the web ui, I'm hoping to restore it to that.
> 
> Many thanks,
> 
> Bren
> Bren,

I'm a bit of a vacation, so give me a bit and I'll help you out, if I 
happen to forget to check back in week or so, email me at 
devgru@riseup.net and remind me.

**Comment by bren1818** [comment]
Hey @hypergolic , just checking in. Am I able to use DD to take your image files, image0_kernal, image1_sqfs, image2_dtv and write them over the partitions on the device? Something is still causing my bridge to bootloop and the sync button does not work. I'm hoping to essentially re-image this to stock firmware if possible. I have another bridge in the meanwhile which is wokring but, I'm no expert with dd, and only really know enough with linux to be dangerous.

thanks,

Bren

**Comment by bren1818** [comment]
**FIXED IT**
Hey @hypergolic, you can close this topic. I was able to fix the issue. For whatever reason, the firmware you had here (both original and modified) would not actually re-flash 'everything' on my device. I could take it from the newer firmware on port 443 to the lower on port 80, but whatever issue had occurred with the device was not resolved.

What I did to resolve was downloaded another image file. Specifically the 2.0.47 file, and flashed it. That binary can be obtained from here: http://update.greenwavereality.eu/roxy/download/1337594376/rootfs.bin
alternatively there was the 3.0.39 firmware here:
http://update.greenwavereality.eu/roxy/download/1386066602/rootfs.bin
or the 3.0.74 firmware here:
http://update.greenwavereality.eu/roxy/download/1410966155/rootfs.bin

Again, using your code, and the 2.0.47 file, I calculated the md5 of it to be: 9e32549d1cbb0d091b45683190e48f89

booted the device holding the sync button and presto-chango, the device came back to life. The sync button now works as it should AND it even remembered the original bulbs I had ported over to my backup bridge.

I will write a detailed instruction on how to use your firmware mod, with the stock firmware file in the event anyone has the same issue I did. I also grabbed the three binaries above as greenwavereality.com is no more.

Thanks!

Bren
